apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: todo-app-ui
  template:
    metadata:
      labels:
        app: todo-app-ui
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/karthik/todo-demo-app
        name: todo-app-ui
        ports:
        - containerPort: 80
